//! Generated SDK client adapter — bridges AppContext to the co-generated SDK.
//!
//! Auto-generated by @fern-api/cli-generator. Do not edit by hand.

#![allow(dead_code)]

use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;

use fern_cli_sdk::error::CliError;
use fern_cli_sdk::openapi::AppContext;
use fern_cli_sdk::sdk_executor::{CliExecutor, SdkError, SdkRequestExecutor};

// ---------------------------------------------------------------------------
// Executor adapter: CliExecutor → SDK RequestExecutor
// ---------------------------------------------------------------------------

struct CliExecutorAdapter(Arc<CliExecutor>);

impl mailchimp_api_sdk::RequestExecutor for CliExecutorAdapter {
    fn execute(
        &self,
        request: reqwest::Request,
    ) -> Pin<
        Box<
            dyn Future<Output = Result<reqwest::Response, Box<dyn std::error::Error + Send + Sync>>>
                + Send
                + '_,
        >,
    > {
        Box::pin(async move {
            SdkRequestExecutor::execute(&*self.0, request)
                .await
                .map_err(|e| Box::new(e) as Box<dyn std::error::Error + Send + Sync>)
        })
    }
}

// ---------------------------------------------------------------------------
// client — construct a fully-wired SDK root client
// ---------------------------------------------------------------------------

/// Build the SDK root client from the CLI's runtime context.
///
/// The returned client routes all HTTP through the CLI's executor, so
/// it inherits auth, retries, TLS, and global headers automatically.
pub fn client(ctx: &AppContext) -> mailchimp_api_sdk::api::ApiClient {
    let executor = ctx.build_sdk_executor();
    let adapter = Arc::new(CliExecutorAdapter(executor));
    // Seed the base URL from the CLI's own resolution (--base-url / env >
    // spec base_url > server root). `ClientConfig::default()` carries an
    // empty `base_url` for any API that declares no environment, which made
    // every custom command fail on a relative URL before the executor ran.
    let config = mailchimp_api_sdk::ClientConfig {
        base_url: ctx.effective_base_url(),
        ..Default::default()
    };
    let http_client = mailchimp_api_sdk::HttpClient::with_executor(
        adapter as Arc<dyn mailchimp_api_sdk::RequestExecutor>,
        config.clone(),
    );
    mailchimp_api_sdk::api::ApiClient {
        config,
        root: mailchimp_api_sdk::api::RootClient { http_client: http_client.clone() },
        account_exports: mailchimp_api_sdk::api::AccountExportsClient { http_client: http_client.clone() },
        activity_feed: mailchimp_api_sdk::api::ActivityFeedClient { http_client: http_client.clone() },
        authorized_apps: mailchimp_api_sdk::api::AuthorizedAppsClient { http_client: http_client.clone() },
        automations: mailchimp_api_sdk::api::AutomationsClient { http_client: http_client.clone() },
        batch_webhooks: mailchimp_api_sdk::api::BatchWebhooksClient { http_client: http_client.clone() },
        batches: mailchimp_api_sdk::api::BatchesClient { http_client: http_client.clone() },
        campaign_folders: mailchimp_api_sdk::api::CampaignFoldersClient { http_client: http_client.clone() },
        campaigns: mailchimp_api_sdk::api::CampaignsClient { http_client: http_client.clone() },
        connected_sites: mailchimp_api_sdk::api::ConnectedSitesClient { http_client: http_client.clone() },
        conversations: mailchimp_api_sdk::api::ConversationsClient { http_client: http_client.clone() },
        customer_journeys: mailchimp_api_sdk::api::CustomerJourneysClient { http_client: http_client.clone() },
        ecommerce: mailchimp_api_sdk::api::EcommerceClient { http_client: http_client.clone() },
        facebook_ads: mailchimp_api_sdk::api::FacebookAdsClient { http_client: http_client.clone() },
        file_manager: mailchimp_api_sdk::api::FileManagerClient { http_client: http_client.clone() },
        landing_pages: mailchimp_api_sdk::api::LandingPagesClient { http_client: http_client.clone() },
        lists: mailchimp_api_sdk::api::ListsClient { http_client: http_client.clone() },
        surveys: mailchimp_api_sdk::api::SurveysClient { http_client: http_client.clone() },
        ping: mailchimp_api_sdk::api::PingClient { http_client: http_client.clone() },
        reporting: mailchimp_api_sdk::api::ReportingClient { http_client: http_client.clone() },
        reports: mailchimp_api_sdk::api::ReportsClient { http_client: http_client.clone() },
        search_campaigns: mailchimp_api_sdk::api::SearchCampaignsClient { http_client: http_client.clone() },
        sms_campaigns: mailchimp_api_sdk::api::SmsCampaignsClient { http_client: http_client.clone() },
        search_members: mailchimp_api_sdk::api::SearchMembersClient { http_client: http_client.clone() },
        template_folders: mailchimp_api_sdk::api::TemplateFoldersClient { http_client: http_client.clone() },
        templates: mailchimp_api_sdk::api::TemplatesClient { http_client: http_client.clone() },
        verified_domains: mailchimp_api_sdk::api::VerifiedDomainsClient { http_client: http_client.clone() },
    }
}

// ---------------------------------------------------------------------------
// block_on — async SDK call → sync handler result
// ---------------------------------------------------------------------------

/// Execute an async SDK operation from a synchronous custom-command handler.
///
/// Bridges the SDK's `ApiError` into the CLI's `CliError` so `?` works
/// naturally in handler bodies.
pub fn block_on<F, T>(future: F) -> Result<T, CliError>
where
    F: Future<Output = Result<T, mailchimp_api_sdk::ApiError>>,
{
    tokio::task::block_in_place(|| {
        let handle = tokio::runtime::Handle::current();
        handle.block_on(future).map_err(convert_api_error)
    })
}

fn convert_api_error(e: mailchimp_api_sdk::ApiError) -> CliError {
    match e {
        mailchimp_api_sdk::ApiError::Http { status, message } => {
            fern_cli_sdk::error::api_error_from_body(status, &message)
        }
        mailchimp_api_sdk::ApiError::Network(err) => {
            CliError::Other(anyhow::anyhow!("SDK network error: {err}"))
        }
        mailchimp_api_sdk::ApiError::Executor(boxed) => match boxed.downcast::<SdkError>() {
            Ok(sdk_error) => sdk_error.into_cli_error(),
            Err(other) => CliError::Other(anyhow::anyhow!("SDK executor error: {other}")),
        },
        other => CliError::Other(anyhow::anyhow!("SDK error: {other}")),
    }
}
